### ISSUE TITLE
Unity Project Template not available

### ISSUE THREAD

**Issue by naveen27b** [mikebind/Heartbeat4D#1]
Hi mike, this is such an inspiring work. Thank you for that. It will be greatly helpful for cardiac surgery planning and learning. I will be glad if you can provide me the unity project template. I want to run this project and experience it in augmented reality. Thanks once again

**Comment by mikebind** [comment]
Hello Naveen, I have uploaded the template to my google drive, and it should be accessible to you at this link:  https://drive.google.com/file/d/182tApJipaAxZ7dIdAYoMjix1DJs64l3N/view?usp=drive_link

My drive is getting full, so I will eventually probably remove this file and it will become unavailable.  However, I will leave it up for at least the next few weeks to give you a chance to retrieve it.

**Comment by hybtalented** [comment]
> Hello Naveen, I have uploaded the template to my google drive, and it should be accessible to you at this link: https://drive.google.com/file/d/182tApJipaAxZ7dIdAYoMjix1DJs64l3N/view?usp=drive_link
> 
> My drive is getting full, so I will eventually probably remove this file and it will become unavailable. However, I will leave it up for at least the next few weeks to give you a chance to retrieve it.

Hello, may I ask if this link is still accessible? I need it for a recent project. @mikebind
